name: "windows tests for 'kiara_plugin.sample_plugin'"
on: [push]

jobs:
  test-windows:
    name: pytest on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/checkout@v4
      - name: install kiara_plugin.sample_plugin
        run: pip install -U .[dev_testing]
      - name: display installed kiara and module package versions
        run: kiara --version
      - name: Test with pytest
        run: make test
